apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-v2-deployment
  labels:
    app: sample-app-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app-v2
  template:
    metadata:
      labels:
        app: sample-app-v2
    spec:
      containers:
        - name: sample-app-v2
          image: krishnetshoppingapp.azurecr.io/sample-ang-app-to-test-apachehosting:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.1"
            limits:
              memory: "128Mi"
              cpu: "0.3"
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app-v2-service
spec:
  type: LoadBalancer
  selector:
    app: sample-app-v2
  ports:
    - protocol: TCP
      port: 80
